"""add hourly booking

Revision ID: 7c26ae672a37
Revises: 7a4ea2e1a94c
Create Date: 2026-07-30 10:24:36.106117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c26ae672a37'
down_revision: Union[str, Sequence[str], None] = '7a4ea2e1a94c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE bookingmode ADD VALUE IF NOT EXISTS 'hourly'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bed_stays', 'start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('bed_stays', 'end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('bookings', sa.Column('total_hours', sa.Integer(), nullable=True))
    op.alter_column('bookings', 'check_in_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('bookings', 'check_out_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('rooms', sa.Column('hourly_rent', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.alter_column('waitlist_entries', 'check_in_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('waitlist_entries', 'check_out_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waitlist_entries', 'check_out_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('waitlist_entries', 'check_in_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('rooms', 'hourly_rent')
    op.alter_column('bookings', 'check_out_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('bookings', 'check_in_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('bookings', 'total_hours')
    op.alter_column('bed_stays', 'end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('bed_stays', 'start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
