"""add student transfer requests

Revision ID: e547c1c574ce
Revises: 8d3f5a9b1c2e
Create Date: 2026-07-30 12:34:31.465400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e547c1c574ce'
down_revision: Union[str, Sequence[str], None] = '8d3f5a9b1c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_transfer_requests',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('from_hostel_id', sa.UUID(), nullable=False),
    sa.Column('to_hostel_id', sa.UUID(), nullable=False),
    sa.Column('to_room_id', sa.UUID(), nullable=True),
    sa.Column('to_bed_id', sa.UUID(), nullable=True),
    sa.Column('transfer_type', sa.Enum('INTERNAL', 'EXTERNAL', name='transfertype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PENDING_OLD_ADMIN', 'PENDING_NEW_ADMIN', 'COMPLETED', 'REJECTED', 'CANCELLED', name='transferstatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('old_admin_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_admin_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_hostel_id'], ['hostels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_bed_id'], ['beds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_hostel_id'], ['hostels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_transfer_requests_from_hostel_id'), 'student_transfer_requests', ['from_hostel_id'], unique=False)
    op.create_index(op.f('ix_student_transfer_requests_status'), 'student_transfer_requests', ['status'], unique=False)
    op.create_index(op.f('ix_student_transfer_requests_student_id'), 'student_transfer_requests', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_transfer_requests_to_bed_id'), 'student_transfer_requests', ['to_bed_id'], unique=False)
    op.create_index(op.f('ix_student_transfer_requests_to_hostel_id'), 'student_transfer_requests', ['to_hostel_id'], unique=False)
    op.create_index(op.f('ix_student_transfer_requests_to_room_id'), 'student_transfer_requests', ['to_room_id'], unique=False)
    op.create_index(op.f('ix_student_transfer_requests_transfer_type'), 'student_transfer_requests', ['transfer_type'], unique=False)
    op.create_index(op.f('ix_student_transfer_requests_user_id'), 'student_transfer_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_transfer_requests_user_id'), table_name='student_transfer_requests')
    op.drop_index(op.f('ix_student_transfer_requests_transfer_type'), table_name='student_transfer_requests')
    op.drop_index(op.f('ix_student_transfer_requests_to_room_id'), table_name='student_transfer_requests')
    op.drop_index(op.f('ix_student_transfer_requests_to_hostel_id'), table_name='student_transfer_requests')
    op.drop_index(op.f('ix_student_transfer_requests_to_bed_id'), table_name='student_transfer_requests')
    op.drop_index(op.f('ix_student_transfer_requests_student_id'), table_name='student_transfer_requests')
    op.drop_index(op.f('ix_student_transfer_requests_status'), table_name='student_transfer_requests')
    op.drop_index(op.f('ix_student_transfer_requests_from_hostel_id'), table_name='student_transfer_requests')
    op.drop_table('student_transfer_requests')
    # ### end Alembic commands ###
